/*
 * This source file was generated by the Gradle 'init' task
 */
package caesarscipher;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        CeasarScipher ceasarScipher = new CeasarScipher();
        String message = "how are you doing today";
        int offset = 12;
        String cipherText = ceasarScipher.cipher(message, offset);
        System.out.println("Cipher text: " + cipherText);

    }
}
