/*
 * This source file was generated by the Gradle 'init' task
 */
package caesarscipher;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private CeasarScipher ceasarScipher = new CeasarScipher();
    @Test 
    void testCipher() {
        assertEquals("tai mdq kag pauzs fapmk", ceasarScipher.cipher("how are you doing today", 12));
    }
}
